// Package asset implements the single object-storage entry point. Business
// modules never import the Qiniu SDK directly; they depend only on ObjectStore.
package asset

import (
	"context"
	"io"
	"net/http"
	"time"
)

// UploadPurpose enumerates the allowed asset purposes (Qiniu spec §3).
type UploadPurpose string

const (
	UploadPurposeAvatar         UploadPurpose = "avatar"
	UploadPurposeStoreLogo      UploadPurpose = "store_logo"
	UploadPurposeStoreContactQR UploadPurpose = "store_contact_qr"
	UploadPurposeCategory       UploadPurpose = "category"
	UploadPurposeProduct        UploadPurpose = "product"
	UploadPurposeActivity       UploadPurpose = "activity"
	UploadPurposeTableLayout    UploadPurpose = "table_layout"
	UploadPurposeSeatLayout     UploadPurpose = "seat_layout"
	UploadPurposeVipIcon        UploadPurpose = "vip_icon"
	UploadPurposeVipBanner      UploadPurpose = "vip_banner"
	UploadPurposeRichContent    UploadPurpose = "rich_content"
)

// Asset visibility.
const (
	VisibilityPublic  = "public"
	VisibilityPrivate = "private"
)

// Asset lifecycle status.
const (
	StatusPending  = "pending"
	StatusUploaded = "uploaded"
	StatusBound    = "bound"
	StatusFailed   = "failed"
	StatusDeleted  = "deleted"
)

// CreateCredentialInput is the server-resolved input for signing an upload token.
// The object key is generated by the server, never by the client.
type CreateCredentialInput struct {
	AssetID      int64
	ObjectKey    string
	MaxSizeBytes int64
	Visibility   string
}

// UploadCredential is returned to the client to perform a direct upload.
type UploadCredential struct {
	AssetID      int64     `json:"assetId"`
	ObjectKey    string    `json:"objectKey"`
	UploadToken  string    `json:"uploadToken"`
	UploadURL    string    `json:"uploadUrl"`
	PublicURL    string    `json:"publicUrl"`
	ExpiresAt    time.Time `json:"expiresAt"`
	MaxSizeBytes int64     `json:"maxSizeBytes"`
}

// CallbackPayload is the verified content of a Qiniu upload callback.
type CallbackPayload struct {
	AssetID  int64  `json:"assetId"`
	Key      string `json:"key"`
	Etag     string `json:"etag"`
	Fsize    int64  `json:"fsize"`
	MimeType string `json:"mimeType"`
	Bucket   string `json:"bucket"`
}

// PublicUploadInput is the server-side input for uploading a public object
// directly (e.g. from a local file or an in-memory reader).
type PublicUploadInput struct {
	ObjectKey   string
	Reader      io.Reader
	SizeBytes   int64
	ContentType string
}

// UploadedObject is the result of a server-side public upload.
type UploadedObject struct {
	ObjectKey string `json:"objectKey"`
	Hash      string `json:"hash"`
	SizeBytes int64  `json:"sizeBytes"`
	PublicURL string `json:"publicUrl"`
}

// ObjectStore is the only interface business code uses for object storage.
type ObjectStore interface {
	CreateUploadCredential(ctx context.Context, input CreateCredentialInput) (UploadCredential, error)
	UploadPublicObject(ctx context.Context, input PublicUploadInput) (UploadedObject, error)
	VerifyUploadCallback(req *http.Request) (CallbackPayload, error)
	PublicURL(objectKey string) string
	PrivateURL(ctx context.Context, objectKey string, ttl time.Duration) (string, error)
	Delete(ctx context.Context, objectKey string) error
	Bucket() string
}
